# docker run --name api-solid-pg -e POSTGRESQL_USERNAME=daniel -e POSTGRESQL_PASSWORD=daniel -e POSTGRESQL_DATABASE=api-solid -p 5432:5432 bitnami/postgresql:latest
version: '3'
services:
  api-solid-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=daniel
      - POSTGRESQL_PASSWORD=daniel
      - POSTGRESQL_DATABASE=api-solid