POST http://localhost:3333/users
Content-Type: application/json

{
    "name": "Daniel",
    "email": "daniel5@mail.com",
    "password": "123456"
}

###
POST http://localhost:3333/sessions
Content-Type: application/json

{
    "email": "daniel5@mail.com",
    "password": "123456"
}