POST http://localhost:3333/user
Content-Type: application/json

{
    "name": "Daniel",
    "email": "daniel5@mail.com",
    "password": "123456"
}

###
POST http://localhost:3333/user/sessions
Content-Type: application/json

{
    "email": "daniel5@mail.com",
    "password": "123456"
}

###
PATCH http://localhost:3333/user/token/refresh

###

GET http://localhost:3333/user/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MjlhMGVkZC00N2U2LTRhZGUtODcyMi1hNjM2OTMyN2U4ZTgiLCJpYXQiOjE3MjcwMzMxNzd9.BMpNh0GUM5TiX92RC6xjUOYf8oh4vT2-L-6NM5edSW4

###
POST http://localhost:3333/gym
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MjlhMGVkZC00N2U2LTRhZGUtODcyMi1hNjM2OTMyN2U4ZTgiLCJpYXQiOjE3MjczMDcxNjN9.OJ0OOl7-rhHINLtxeYA3kSqJj_JGNlXKAhUwTE0bFlw

{
    "title": "Outfit 2",
    "description": "Cadimia aqui pertin 2",
    "phone": "",
    "latitude": -19.9525922,
    "longitude": -43.999216
}

###
GET http://localhost:3333/gym?query=Outfit 2&page=1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MjlhMGVkZC00N2U2LTRhZGUtODcyMi1hNjM2OTMyN2U4ZTgiLCJpYXQiOjE3MjczMDcxNjN9.OJ0OOl7-rhHINLtxeYA3kSqJj_JGNlXKAhUwTE0bFlw

###
GET http://localhost:3333/gym/nearby?latitude=-19.9525922&longitude=-43.999216
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MjlhMGVkZC00N2U2LTRhZGUtODcyMi1hNjM2OTMyN2U4ZTgiLCJpYXQiOjE3MjczMTIzMzF9.sTXrprIeoNnWjUTw1rsYR6CdWbEvoyISCbf_tF1bgrU

###
POST http://localhost:3333/gym/60f2f594-f573-44e3-8706-f925ec933603/check-in
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MjlhMGVkZC00N2U2LTRhZGUtODcyMi1hNjM2OTMyN2U4ZTgiLCJpYXQiOjE3MjczMTIzMzF9.sTXrprIeoNnWjUTw1rsYR6CdWbEvoyISCbf_tF1bgrU

{
    "latitude": -19.9525922,
    "longitude": -43.999216
}

###
GET http://localhost:3333/check-ins/history
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MjlhMGVkZC00N2U2LTRhZGUtODcyMi1hNjM2OTMyN2U4ZTgiLCJpYXQiOjE3MjczMTIzMzF9.sTXrprIeoNnWjUTw1rsYR6CdWbEvoyISCbf_tF1bgrU

###
POST http://localhost:3333/check-ins/:checkinId/validate
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MjlhMGVkZC00N2U2LTRhZGUtODcyMi1hNjM2OTMyN2U4ZTgiLCJpYXQiOjE3MjczMTIzMzF9.sTXrprIeoNnWjUTw1rsYR6CdWbEvoyISCbf_tF1bgrU

{
    "latitude": -19.9525922,
    "longitude": -43.999216
}