name: Run Unit Tests

on: [push]

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      # baixa o código para a máquina ubuntu definida em runs-on
      - uses: actions/checkout@v3
      # configura a versão do node
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          # se não houver mudanças nas dependências, o workflow reaproveita o cache criado
          cache: 'npm'
      - run: npm ci
      - run: npm run test