name: Run E2E Tests

on: [pull_request]

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      db_postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: daniel
          POSTGRESQL_PASSWORD: daniel
          POSTGRESQL_DATABASE: api-solid

    steps:
      # baixa o código para a máquina ubuntu definida em runs-on
      - uses: actions/checkout@v3
      # configura a versão do node
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          # se não houver mudanças nas dependências, o workflow reaproveita o cache criado
          cache: 'npm'
      - run: npm ci
      - run: npm run test:e2e
        env:
          JWT_SECRET: testing
          DATABASE_URL: "postgresql://daniel:daniel@localhost:5432/mydb?schema=api-solid"